name: build

on:
  workflow_dispatch:
  

jobs:
  build:
    runs-on: windows-latest
    env:
      VS_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\
      MSBUILD_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: Build XInput Release
        run: '"%MSBUILD_PATH%\MSBuild.exe" AmongUsMenu.vcxproj /p:Platform=Win32 /p:Configuration=Release_Xinput'
