name: build

on:
  workflow_dispatch:
  

jobs:
  build:
    runs-on: windows-latest
    env:
      VS_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\
      MSBUILD_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
        
      - name: Build XInput Release
        run: msbuild /p:Configuration=Release_Xinput /p:Platform=x86
