name: build

on:
  workflow_dispatch:
  

jobs:
  build:
    runs-on: windows-latest
    env:
      MSBUILD: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      - name: Build XInput Release
        shell: cmd
        run: '"%MSBUILD%" /p:Configuration=Release_Xinput /p:Platform=x86'
        
      #- name: Zip Release
      #  working-directory: Release_Xinput
        
